from enum import StrEnum, auto


class СathedralSlug(StrEnum):
    pravila_svjatyh_apostolov = auto()
    svjatogo_apostola_pavla_osobno_pravil = auto()
    togo_zh_pravila_o_usopshih_i_vlasteleh = auto()
    vselenskij_sobor_1_nikejskij = auto()
    pomestnyj_sobor_ankirskij = auto()
    pomestnyj_sobor_neokesarijskij = auto()
    pomestnyj_sobor_gangrskij = auto()
    pomestnyj_sobor_antiohijskij = auto()
    pomestnyj_sobor_laodikijskij = auto()
    vselenskij_sobor_2_konstantinopolskij = auto()
    vselenskij_sobor_3_efesskij = auto()
    vselenskij_sobor_4_halkidonskij = auto()
    pomestnyj_sobor_sardikijskij = auto()
    pomestnyj_sobor_karfagenskij = auto()
    vselenskij_sobor_6_konstantinopolskij_trulskij = auto()
    vselenskij_sobor_7_nikejskij = auto()
    pomestnyj_sobor_konstantinopolskij_dvukratnyj = auto()
    pomestnyj_sobor_konstantinopolskij = auto()
    pravila_svjatogo_vasilija_velikogo_ot_poslanij = auto()
    svjatago_vasilja_o_vremeni_sogreshajuschih_vkrattse = auto()
    iustinijana_razlichnyja_zapovedi = auto()
