version: "3.8"
services:

  nginx-frontend:
    container_name: nginx-frontend
    image: cr.yandex/crpt1bjls9dnr4c3c3bu/nginx-frontend:latest
    expose:
      - 80
    ports:
      - "80:80"
    restart: always
    networks:
      - custom

networks:
  custom:
    driver: bridge
