version: "3.8"
services:

  redis:
    container_name: redis
    image: cr.yandex/mirror/redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "6379"
    networks:
      - custom
  backend:
    container_name: backend
    image: cr.yandex/crpt1bjls9dnr4c3c3bu/backend:latest
    depends_on:
      - redis
    command: bash -c "start_server.production.sh"
    expose:
      - "8000"
    environment:
      - INSTALL_DEV=true
      - DOMAIN=localhost
      - STACK_NAME=app-com
      - DOCKER_IMAGE_BACKEND=backend
      - DOCKER_IMAGE_FRONTEND=frontend
      # Backend
      - BACKEND_CORS_ORIGINS=["http://158.160.102.206:80", "http://158.160.102.206:80/", "http://nginx-frontend:80", "http://localhost:4173", "http://localhost:5173", "http://localhost:5174", "http://localhost:5175", "http://localhost:5176", "http://localhost:8000", "http://localhost:8080", "http://localhost:8081", "http://localhost:81", "http://localhost:80"]
      - PROJECT_NAME=app
      - SECRET_KEY=kopkop99 # скорее всего нет
      - SMTP_TLS=True
      - SMTP_PORT=587
      - EMAILS_FROM_EMAIL=info@fastapi.com
      # Object Storage
      - AWS_ACCESS_KEY_ID=YCAJEYqFyyPNzvAPRNLsZb3CF
      - AWS_SECRET_ACCESS_KEY=YCPttFsHNXOPqRVOPrvnTipjk3tCq5f2Pfgpzlya
      - OBJECT_STORAGE_BUCKET_NAME=pravoslavie16v.ru
      # Postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=kopkop99
      - POSTGRES_SERVER=rc1a-72x7dd2xeqw4ztpl.mdb.yandexcloud.net
      - POSTGRES_PORT=6432
      - POSTGRES_DB=db
      # Tg
      - TG_BOT_TOKEN=6787487479:AAEdSY3In7zM6P52OMpqfKCr7DhlUqqg7Bo
      - TG_CHANNEL_ID=@pravoslavie16v
      # Vk
      - VK_GROUP_ID=223411062
      - VK_ACCESS_TOKEN=vk1.a.H3S4pMcy1DzEIUz0pwpts2qqjezflRjozukDj5BPmMPWcso8Wm8efEArKIxuqRvjWZZ8tKUN3LD0st61fynAH09gALKXDIKzLr6JrCy3XgHFaB_sApBAf7nmtE5C263dndO0o0pHTCQ1vaxvompYT6OLn-ndbmG6c5TqIWl5echP3KdGLvEKqNrjH64Bh1h4
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - custom
  nginx-backend:
    container_name: nginx-backend
    image: cr.yandex/crpt1bjls9dnr4c3c3bu/nginx-backend:latest
    expose:
      - 81
    ports:
      - "81:80"
    restart: always
    depends_on:
      - backend
    networks:
      - custom

networks:
  custom:
    driver: bridge

