version: "3.8"
services:

  redis:
    container_name: redis
    image: cr.yandex/mirror/redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "6379"
    networks:
      - custom
  backend:
    container_name: backend
    image: cr.yandex/crpt1bjls9dnr4c3c3bu/backend:latest
    depends_on:
      - redis
    command: bash -c "start_server.production.sh"
    expose:
      - "8000"
    networks:
      - custom
  nginx-backend:
    container_name: nginx-backend
    image: cr.yandex/crpt1bjls9dnr4c3c3bu/nginx-backend:latest
    expose:
      - 81
    ports:
      - "81:80"
    restart: always
    depends_on:
      - backend
    networks:
      - custom

networks:
  custom:
    driver: bridge

