version: "3.8"
services:

  redis:
    container_name: redis
    image: cr.yandex/mirror/redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "6379"
    networks:
      - custom
  backend:
    container_name: backend
    image: cr.yandex/crp085obp8dj4e4q9hd3/backend:latest
    depends_on:
      - redis
    command: bash -c "start_server.production.sh"
    expose:
      - "8000"
    environment:
      - INSTALL_DEV=true
      - DOMAIN=localhost
      - STACK_NAME=app-com
      - DOCKER_IMAGE_BACKEND=backend
      - DOCKER_IMAGE_FRONTEND=frontend
      # Backend
      - BACKEND_CORS_ORIGINS=["http://51.250.6.156:80", "http://51.250.6.156:80/", "http://nginx-frontend:80", "http://localhost:4173", "http://localhost:5173", "http://localhost:5174", "http://localhost:5175", "http://localhost:5176", "http://localhost:8000", "http://localhost:8080", "http://localhost:8081", "http://localhost:81", "http://localhost:80"]
      - PROJECT_NAME=app
      - SECRET_KEY=kopkop99 # скорее всего нет
      - SMTP_TLS=True
      - SMTP_PORT=587
      - EMAILS_FROM_EMAIL=info@fastapi.com
      # Object Storage
      - AWS_ACCESS_KEY_ID=YCAJEoxq5XaxxUEtXz82PDw3p
      - AWS_SECRET_ACCESS_KEY=YCNgZZFc1FHcN7Z549vEIIsEsyWqx5tWWFnfjTdf
      - OBJECT_STORAGE_BUCKET_NAME=pravoslavie16.ru
      # Postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=kopkop99
      - POSTGRES_SERVER=rc1a-2lz9baduguaj0cnx.mdb.yandexcloud.net
      - POSTGRES_PORT=6432
      - POSTGRES_DB=db
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - custom
  nginx-backend:
    container_name: nginx-backend
    image: cr.yandex/crp085obp8dj4e4q9hd3/nginx-backend:latest
    expose:
      - 81
    ports:
      - "81:80"
    restart: always
    depends_on:
      - backend
    networks:
      - custom

networks:
  custom:
    driver: bridge

