from app import schemas, enums

lls_book_7 = (
    [],
    4
)

lls_book_8 = (
    [],
    4
)

lls_book_9 = (
    [],
    4
)

lls_book_10 = (
    [],
    4
)


lls_book_rus_5 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-avraamij-bolgarskij-vladimirskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            249,
            252
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-aleksandr-v-shime-aleksij-nevskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            479,
            489
        ),
        # ? ОБРАБОТАТЬ: О битве и о победе на Неве, о явлении святых мучеников Бориса и Глеба и ангельской помощи, и о шести храбрецах
    ],
    4
)

lls_book_rus_6 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-varlaam-hutynskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Upominanie
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            34,
            34
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-mihail-chernigovskij-i-feodor-chernigovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            52,
            109
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-aleksandr-v-shime-aleksij-nevskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            225,
            229
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-roman-olegovich',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            292,
            295
        ),
    ],
    3
)

lls_book_rus_7 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-mihail-jaroslavich-tverskoj',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            176,
            215
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            261,
            282
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-stefan-urosh-iii',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            309,
            342
        ),
    ],
    4
)

lls_book_rus_8 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-antonij-vilenskij-litovskij-i-ioann-vilenskij-litovskij-i-evstafij-vilenskij-litovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            53,
            54
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            55,
            56
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            73,
            73
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            94,
            95
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-feognost-kievskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            136,
            137
        ),
        (
            schemas.TopicBookDataCreate(
                topic_book_in=schemas.TopicBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            336,
            348
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            466,
            467
        ),
    ],
    4
)

lls_book_rus_9 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-aleksij-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            168,
            221
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='obretenie-moschej-aleksij-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            222,
            224
        ),
    ],
    4
)

lls_book_rus_10 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='presvjataja-vladychitsa-nasha-bogoroditsa-i-prisnodeva-marija',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            117,
            122
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-dionisij-suzdalskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            155,
            156
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='isaakij-molchalnik-troickij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            201,
            202
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-marija-egipetskaja',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Slovo
                    )
                )
            ),
            311,
            312
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-dimitrij-donskoj',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            392,
            429
        ),
    ],
    4
)

lls_book_rus_11 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-sergij-radonezhskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            4,
            115
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-feodor-rostovskij-svjatitel',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            78,
            93
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-andronik-moskovskij-i-savva-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            93,
            95
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-afanasij-serpuhovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            96,
            97
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-feodor-rostovskij-svjatitel',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Upominanie
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            167,
            167
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            171,
            171
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='sretenie-vladimirskoj-ikony-presvjatoj-bogorodicy-prazdnestvo-ustanovleno-v-pamjat-spasenija-moskvy-ot-nashest',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            179,
            294
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-stefan-permskij-velikopermskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            336,
            347
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-mihail-aleksandrovich-tverskoj',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            432,
            480
        ),
    ],
    2
)

lls_book_rus_12 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-kiprian-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            85,
            97
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-evfrosinija-v-miru-evdokija-moskovskaja',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Skazanie
                    )
                )
            ),
            116,
            128
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-arsenij-tverskoj',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            228,
            234
        ),
        (
            schemas.TopicBookDataCreate(
                topic_book_in=schemas.TopicBookCreate(),
                topics_titles=[
                    enums.BookTopic.o_Dolgoterpenii,
                ],
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.slovo_istorija
                    )
                )
            ),
            270,
            273
        ),
        (
            schemas.TopicBookDataCreate(
                topic_book_in=schemas.TopicBookCreate(),
                topics_titles=[
                    enums.BookTopic.o_Svjatyh_Ikonah,
                    enums.BookTopic.o_pjanstve
                ],
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.slovo_istorija
                    )
                )
            ),
            324,
            341
        ),
    ],
    4
)

lls_book_rus_13 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-stefan-shchiljanovich',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            30,
            42
        ),
    ],
    4
)
