from app import schemas, enums

lls_book_rus_5 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-avraamij-bolgarskij-vladimirskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            249,
            252
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-aleksandr-v-shime-aleksij-nevskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            479,
            489
        ),
        # ? ОБРАБОТАТЬ: О битве и о победе на Неве, о явлении святых мучеников Бориса и Глеба и ангельской помощи, и о шести храбрецах
    ],
    4
)

lls_book_rus_6 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-varlaam-hutynskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Upominanie
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            34,
            34
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-mihail-chernigovskij-i-feodor-chernigovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            52,
            109
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-aleksandr-v-shime-aleksij-nevskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            225,
            229
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-roman-olegovich',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            292,
            295
        ),
    ],
    3
)

lls_book_rus_7 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-mihail-jaroslavich-tverskoj',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            176,
            215
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            261,
            282
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-stefan-urosh-iii',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            309,
            342
        ),
    ],
    4
)

lls_book_rus_8 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-antonij-vilenskij-litovskij-i-ioann-vilenskij-litovskij-i-evstafij-vilenskij-litovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            53,
            54
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            55,
            56
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            73,
            73
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            94,
            95
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-feognost-kievskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            136,
            137
        ),
        (
            schemas.TopicBookDataCreate(
                topic_book_in=schemas.TopicBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            336,
            348
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='petr-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(
                    book_util=enums.BookUtil.Chudo
                ),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            466,
            467
        ),
    ],
    4
)

lls_book_rus_9 = (
    [
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='den-pamjati-aleksij-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                        type=enums.BookType.Povest
                    )
                )
            ),
            168,
            221
        ),
        (
            schemas.HolidayBookDataCreate(
                holiday_slug='obretenie-moschej-aleksij-moskovskij',
                holiday_book_in=schemas.HolidayBookCreate(),
                book_data_in=schemas.BookDataCreate(
                    book_in=schemas.BookCreate(
                        title=enums.BookTitle.Lls,
                    )
                )
            ),
            222,
            224
        ),
    ],
    4
)
