from enum import StrEnum


class CityTitle(StrEnum):
    afon = 'Афон'
    balkany = 'Балканы'
    bolgarija = 'Болгария'
    vatoped = 'Ватопед'
    venetsija = 'Венеция'
    vizantija = 'Византия'
    vladimir = 'Владимир'
    vologda = 'Вологда'
    volokolamsk = 'Волоколамск'
    germanija = 'Германия'
    grachanitsa = 'Грачаница'
    gretsija = 'Греция'
    gruzija = 'Грузия'
    dafni = 'Дафни'
    dechani = 'Дечани'
    italija = 'Италия'
    kastorija = 'Кастория'
    kiev = 'Киев'
    kipr = 'Кипр'
    konstantinopol = 'Константинополь'
    makedonija = 'Македония'
    meteory = 'Метеоры'
    milan = 'Милан'
    moskva = 'Москва'
    nereditsa = 'Нередица'
    novgorod = 'Новгород'
    ohrid = 'Охрид'
    pskov = 'Псков'
    ravenna = 'Равенна'
    rim = 'Рим'
    rostov = 'Ростов'
    rumynija = 'Румыния'
    russkij_sever = 'Русский Север'
    rus = 'Русь'
    saloniki = 'Салоники'
    serbija = 'Сербия'
    sirija = 'Сирия'
    sitsilija = 'Сицилия'
    solun = 'Солунь'
    solvychegodsk = 'Сольвычегодск'
    sopochany = 'Сопочаны'
    tver = 'Тверь'
    ferapontovo = 'Ферапонтово'
    hosios_lukas = 'Хосиос Лукас'
    chefalu = 'Чефалу'
    jaroslavl = 'Ярославль'

    velikij_novgorod = 'Великий Новгород'
    kavkaz_gruzija = 'Кавказ, Грузия'
    perejaslavl_zalesskij = 'Переяславль-Залесский'
    rossija = 'Россия'

    belorussija = 'Белоруссия'
    velikij_ustjug = 'Великий Устюг'
    vizantija_konstantinopol = 'Византия, Константинополь'
    vologodskie_zemli = 'Вологодские земли'
    vostochnaja_evropa_serbija = 'Восточная Европа, Сербия'
    gretsija_afon = 'Греция, Афон'
    gretsija_krit = 'Греция, Крит'
    zapadnaja_evropa_gretsija_afon = 'Западная Европа, Греция, Афон'
    zapadnaja_evropa_gretsija_krit = 'Западная Европа, Греция, Крит'
    zapadnaja_evropa_italija = 'Западная Европа, Италия'
    zapadnaja_evropa_italija_venetsija = 'Западная Европа, Италия, Венеция'
    krit = 'Крит'
    krym = 'Крым'
    novgorod_ili_russkij_sever = 'Новгород или Русский Север'
    novgorodskaja_provintsija = 'Новгородская провинция'
    provintsija = 'Провинция'
    rossija_provintsija = 'Россия (Провинция)'
    sever = 'Север'
    severo_vostochnaja_rus_rostovskaja_shkola = 'Северо-восточная Русь, Ростовская школа'
    solovetskij_monastyr = 'Соловецкий монастырь'
    srednjaja_rus = 'Средняя Русь'
    tihvin = 'Тихвин'
    tsentralnaja_moskva = 'Центральная Москва'
    tsentralnaja_rossija = 'Центральная Россия'
    jaroslavskaja_obl_jaroslavl = 'Ярославская обл., Ярославль'


class CountryTitle(StrEnum):
    rus = 'Русь'
    gretsija = 'Греция'  # 14..
    rim = 'Рим'


class CityCountryTitle(StrEnum):
    afon = CountryTitle.gretsija
    balkany = CountryTitle.gretsija
    bolgarija = 'Болгария'
    vatoped = CountryTitle.gretsija
    venetsija = CountryTitle.rim
    vizantija = CountryTitle.gretsija
    vladimir = CountryTitle.rus
    vologda = CountryTitle.rus
    volokolamsk = CountryTitle.rus
    germanija = 'Германия'
    grachanitsa = 'Грачаница'
    gretsija = CountryTitle.gretsija
    gruzija = 'Грузия'
    dafni = CountryTitle.gretsija
    dechani = CountryTitle.gretsija
    italija = CountryTitle.rim
    kastorija = CountryTitle.gretsija
    kiev = CountryTitle.rus
    kipr = 'Кипр'
    konstantinopol = CountryTitle.gretsija
    makedonija = 'Македония'
    meteory = CountryTitle.gretsija
    milan = CountryTitle.rim
    moskva = CountryTitle.rus
    nereditsa = CountryTitle.rus
    novgorod = CountryTitle.rus
    ohrid = CountryTitle.gretsija  # ?
    pskov = CountryTitle.rus
    ravenna = CountryTitle.rim
    rim = CountryTitle.rim
    rostov = CountryTitle.rus
    rumynija = 'Румыния'
    russkij_sever = CountryTitle.rus
    rus = CountryTitle.rus
    saloniki = CountryTitle.gretsija
    serbija = 'Сербия'
    sirija = 'Сирия'
    sitsilija = 'Сицилия'
    solun = CountryTitle.gretsija
    solvychegodsk = CountryTitle.rus
    sopochany = 'Сопочаны'
    tver = CountryTitle.rus
    ferapontovo = CountryTitle.rus
    hosios_lukas = 'Хосиос Лукас'
    chefalu = 'Чефалу'
    jaroslavl = CountryTitle.rus

    velikij_novgorod = CountryTitle.rus
    kavkaz_gruzija = 'Кавказ, Грузия'
    perejaslavl_zalesskij = CountryTitle.rus
    rossija = CountryTitle.rus

    belorussija = CountryTitle.rus
    velikij_ustjug = CountryTitle.rus
    vizantija_konstantinopol = CountryTitle.gretsija
    vologodskie_zemli = CountryTitle.rus
    vostochnaja_evropa_serbija = 'Восточная Европа, Сербия'
    gretsija_afon = CountryTitle.gretsija
    gretsija_krit = CountryTitle.gretsija
    zapadnaja_evropa_gretsija_afon = CountryTitle.gretsija
    zapadnaja_evropa_gretsija_krit = CountryTitle.gretsija
    zapadnaja_evropa_italija = CountryTitle.rim
    zapadnaja_evropa_italija_venetsija = CountryTitle.rim
    krit = CountryTitle.gretsija
    krym = CountryTitle.rim
    novgorod_ili_russkij_sever = CountryTitle.rus
    novgorodskaja_provintsija = CountryTitle.rus
    provintsija = CountryTitle.rus
    rossija_provintsija = CountryTitle.rus
    sever = CountryTitle.rus
    severo_vostochnaja_rus_rostovskaja_shkola = CountryTitle.rus
    solovetskij_monastyr = CountryTitle.rus
    srednjaja_rus = CountryTitle.rus
    tihvin = CountryTitle.rus
    tsentralnaja_moskva = CountryTitle.rus
    tsentralnaja_rossija = CountryTitle.rus
    jaroslavskaja_obl_jaroslavl = CountryTitle.rus
