import logging
from datetime import date

import requests
from sqlalchemy.orm import Session

from app import crud, models
from app.api import deps
from app.const import BASE_YEAR_FOR_DAY
from app.create.prepare.icon import __collect
from app.utils import int_date2date


def __set_base_year_for_day(some_date: date) -> date:
    some_date = date(BASE_YEAR_FOR_DAY, some_date.month, some_date.day)
    return some_date


def __set_base_year_for_days(some_dates: list[date]) -> list[date]:
    some_dates: list[date] = [__set_base_year_for_day(day) for day in some_dates]
    return some_dates


if __name__ == '__main__':
    db: Session = next(deps.get_db())
    session: requests.Session = next(deps.get_session())
    # pravicon_saints_ids: list[tuple[str, int]] = get_pravicon_saints_ids(db, session=session)
    pravicon_saints_ids = [('ermionija', 1802), ('vavila-nikomidijskij', 1335), ('avdij-persidskij', 1008),
                           ('romil-rimskij', 2795),
                           ('ioann-novgorodskij', 1926), ('pavel-pecherskij-poslushlivyj', 2635), ('varipsav', 1355),
                           ('feodora-aleksandrijskaja-mladshaja', 3079), ('avtonom-italijskij', 1032),
                           ('akakij-melitinskij-svjatitel', 1074),
                           ('porfirij-efesskij', 2744), ('melitina-markianopolskaja', 2428),
                           ('evmenij-gortinskij', 1694),
                           ('daniil-shuzhgorskij', 1611), ('iona-palestinskij', 2014), ('sergij-radonezhskij', 2868),
                           ('pafnutij-tentirskij', 2681), ('epiharija-rimskaja', 1792),
                           ('hariton-sjanzhemskij-prostoj', 3189),
                           ('kiriak-palestinskij-otshelnik', 2152), ('haritina-amisijskaja-pontijskaja', 3186),
                           ('mamelhva-persidskaja', 2351), ('foma-didim-bliznec', 3173),
                           ('martinian-belozerskij', 2396),
                           ('pelagija-tarsijskaja', 2688), ('amfilohij-pecherskij', 1150),
                           ('feofil-tiveriopolskij', 3134),
                           ('amfilohij-glushickij', 1148), ('veniamin-persidskij', 1420), ('lukian-pecherskij', 2301),
                           ('artemij-verkolskij', 1278), ('ilarion-velikij', 1896), ('elisej-lavrishevskij', 1774),
                           ('anastasij-akvilejskij', 1155), ('lupp-solunskij-fessalonikijskij', 2307),
                           ('nestor-pecherskij-neknizhnyj', 2513),
                           ('paraskeva-pjatnica', 2666), ('evtropija-aleksandrijskaja', 1726),
                           ('merkurij-pecherskij', 2437),
                           ('iona-novgorodskij', 2013), ('varlaam-hutynskij', 1365), ('zosima-vorbozomskij', 1835),
                           ('orest-tianskij-kappadokijskij', 2613), ('georgij-pobedonosec', 1515),
                           ('filipp-apostol', 3150),
                           ('grigorij-chudotvorec', 1580), ('nikon-radonezhskij', 2575), ('varlaam-pecherskij', 1362),
                           ('prokopij-kesarijskij-palestinskij', 2762), ('menign', 2435), ('alipij-stolpnik', 1131),
                           ('iakov-persijanin', 1858), ('iakov-rostovskij', 1859),
                           ('feodor-rostovskij-svjatitel', 3066),
                           ('filumen-ankirskij', 3161), ('afanasij-pecherskij-zatvornik', 1302),
                           ('ioann-bezmolvnik-molchalnik', 1974),
                           ('gurij-kazanskij', 1582), ('amvrosij-mediolanskij', 1139),
                           ('ioann-pecherskij-postnik', 1963),
                           ('foma-defurkin', 3172), ('lukija-sirakuzskaja', 2305), ('sevastian-sohotskij', 2842),
                           ('modest-ierusalimskij', 2476), ('grigorij-omiritskij', 1557), ('ignatij-pecherskij', 1875),
                           ('iulianija-nikomidijskaja', 2094), ('femistoklej-mirlikijskij', 3039),
                           ('feoktist-novgorodskij', 3110),
                           ('naum-ohridskij', 2496), ('evfimij-sardijskij', 1739), ('nikanor', 2519),
                           ('emilija-kesarijskaja-kappadokijskaja', 1783), ('ahila-pecherskij', 1317),
                           ('grigorij-pecherskij', 1575),
                           ('paisij-uglichskij', 2651), ('polievkt-melitinskij', 2733), ('antonij-dymskij', 1218),
                           ('makarij-velikij', 2315),
                           ('arsenij-kerkirskij', 4050), ('maksim-grek', 2338), ('agnija-anna-rimskaja', 1057),
                           ('ioann-kazanskij', 1944),
                           ('moisej-novgorodskij', 2479), ('feodor-studit', 3070), ('efrem-pecherskij', 1813),
                           ('roman-uglichskij', 2794),
                           ('isidor-pelusiot', 2074), ('nikolaj-studijskij', 2562), ('vukol-smirnskij', 1467),
                           ('savva-ii-serbskij', 2807),
                           ('anna-novgorodskaja', 1203), ('longin-korjazhemskij', 2286), ('meletij-antiohijskij', 2424),
                           ('evlogij-aleksandrijskij', 1693), ('avksentij-vifinskij', 1017), ('onisim', 2599),
                           ('feodor-tiron', 3073),
                           ('mina-aleksandrijskij', 2447), ('dosifej-palestinskij', 1668), ('lev-katanskij', 2258),
                           ('agafon-pecherskij', 1049), ('polikarp-smirnskij', 2737), ('erazm-pecherskij', 1794),
                           ('tit-pecherskij', 2999),
                           ('vasilij-dekapolit', 1385), ('nestor-pergijskij-magiddijskij', 2512),
                           ('feoktirist-feostirikt-medikijskij', 3108),
                           ('antonina-nikejskaja', 1235), ('arsenij-tverskoj', 1272), ('daniil-moskovskij', 1605),
                           ('erm-erma', 1796),
                           ('sofronij-ierusalimskij', 2941), ('sofronij-pecherskij-zatvornik', 2943),
                           ('nikifor-i-konstantinopolskij', 2533),
                           ('aleksandr-pidnskij', 1101), ('papa-larandskij-selevkijskij', 2661), ('aleksandr-i', 1088),
                           ('aleksij-chelovek-bozhij', 1118), ('kirill-ierusalimskij', 2159),
                           ('foma-konstantinopolskij', 3174),
                           ('nikon-pecherskij', 2573), ('zakharija-pecherskij-postnik', 1821),
                           ('matrona-solunskaja-fessalonikijskaja', 2416),
                           ('evstratij-pecherskij', 1717), ('evvula-nikomidijskaja', 1673),
                           ('ipatij-pecherskij-celebnik', 2036),
                           ('ipatij-rufianskij', 2037), ('marija-egipetskaja', 2367),
                           ('gerontij-pecherskij-kanonarh', 1541),
                           ('iosif-pesnopisec', 2028), ('iosif-pecherskij-mnogoboleznennyj', 2029),
                           ('evtihij-konstantinopolskij', 1720),
                           ('platonida-sirskaja', 4115), ('antipa-pergamskij', 1210),
                           ('ioann-solunskij-fessalonikijskij', 1967),
                           ('zinon-veronijskij', 1828), ('afanasija-eginskaja', 3275), ('zosima-soloveckij', 1837),
                           ('anastasij-sinajskij', 1159), ('vitalij-aleksandrijskij', 1442),
                           ('stefan-permskij-velikopermskij', 2959),
                           ('stefan-pecherskij-vladimiro-volynskij', 2960), ('kirill-turovskij', 2166),
                           ('donat-evrijskij', 1661),
                           ('gerasim-boldinskij', 1520), ('afanasij-velikij', 1290), ('petr-argosskij', 2692),
                           ('alvian-anejskij', 1136),
                           ('irina-makedonskaja', 2049), ('nil-sorskij', 2581), ('arsenij-velikij', 1261),
                           ('simon-zilot', 2904),
                           ('aleksandr-rimskij', 1104), ('isidor-hiosskij', 2076), ('evpl-katanskij-sicilijskij', 1699),
                           ('leontij-ierusalimskij', 2273), ('isaija-rostovskij', 2072), ('ahillij-larisijskij', 1318),
                           ('vasilisk-komanskij', 1408), ('leontij-rostovskij', 2278), ('paisij-galichskij', 2648),
                           ('nikita-stolpnik-perejaslavskij', 2529), ('ioann-psihait', 1968),
                           ('ferapont-monzenskij', 3138),
                           ('nikita-halkidonskij', 2530), ('ermij-komanskij', 1800), ('dionisij-glushickij', 1635),
                           ('mefodij-peshnoshskij', 2443), ('dorofej-tirskij', 1664),
                           ('dorofej-palestinskij-avva', 1663),
                           ('kirill-belozerskij', 2157), ('siluan-pecherskij', 2881), ('arsenij-konevskij', 1265),
                           ('elisej-sumskij', 1777),
                           ('lazar-serbskij', 2254), ('tihon-amafuntskij', 3002), ('leontij-pecherskij', 2276),
                           ('mefodij-patarskij', 2442),
                           ('mina-polockij', 2449), ('evsevij-samosatskij', 1707), ('dionisij-suzdalskij', 1645),
                           ('martin-turovskij', 2394),
                           ('petr-ordynskij', 2710), ('iakinf-rimskij-muchenik', 1844), ('feodor-kirinejskij', 3054),
                           ('sisoj-velikij', 2917),
                           ('kiriakija-nikomidijskaja', 2153), ('feodor-edesskij', 3052),
                           ('apollonij-ikonijskij', 1242), ('matfij', 2420),
                           ('maksim-ispovednik', 2340), ('alipij-pecherskij', 1130), ('ioann-rylskij', 1972),
                           ('irinej-lionskij', 2057),
                           ('adrian-ondrusovskij', 1066), ('aleksandr-svirskij', 1107), ('kiprian-karfagenskij', 2144),
                           ('petr-do-prizvanija-simon', 4053), ('varfolomej-nafanail', 1377),
                           ('tihik-kolofonskij', 3001),
                           ('krisp-jeginskij', 2226), ('andronik-pannonijskij', 1194), ('trofim', 3015),
                           ('sila-korinfskij', 2878),
                           ('aristarh-apamejskij', 1250), ('filipp', 3150), ('epenet-karfagenskij', 1787),
                           ('kesar-dirrahijskij', 2134),
                           ('pud', 2775), ('akila-geraklejskij', 1080), ('iust-rimskij', 2100),
                           ('emilian-dorostolskij', 1781),
                           ('paisij-pecherskij', 2650), ('hristina-tirskaja', 3196), ('moisej-ugrin-vengr', 2482),
                           ('panteleimon-celitel', 2660), ('kallinik-kilikijskij-gangrskij', 2110),
                           ('ioann-voin', 1935),
                           ('german-soloveckij', 1536), ('stefan-i-rimskij', 2961),
                           ('pimen-pecherskij-mnogoboleznennyj', 2722),
                           ('grigorij-sinait', 1577), ('urvan-makedonskij', 3021), ('parmen', 2669),
                           ('kuart-kvart', 2240),
                           ('olimp-olimpan', 2594), ('alfej-kapernaumskij', 1133), ('fortunat', 3177),
                           ('karp-berijskij-makedonskij', 2122),
                           ('stahij-vizantijskij', 2947), ('ahaik', 1315), ('evod-antiohijskij', 1698),
                           ('erast-paneadskij', 1795),
                           ('agav', 1033), ('iona', 2018), ('varuh-prorok', 1375), ('naum', 2497), ('avvakum', 1003),
                           ('aggej', 1054),
                           ('ieremija-prorok', 1885), ('amos', 1145), ('ilija-fesvitjanin', 1914),
                           ('moisej-bogovidec', 2477),
                           ('osija', 2615), ('avdij', 1009), ('malahija', 2348), ('isaija-prorok', 2071),
                           ('iezekiil', 1882),
                           ('azarija-vavilonskij', 1071), ('antonin-makkavej', 1232), ('eleazar-makkavej', 1760),
                           ('alim-makkavej', 1129),
                           ('feodor-kandavlskij', 3053), ('kion-nikomidijskij', 2142), ('fifail', 3164),
                           ('fiveja-viveja', 3140),
                           ('maksim-antiohijskij', 2336), ('zinon-melitinskij', 1829), ('aviv-aleksandrijskij', 1013),
                           ('minodora-vifinskaja', 2450), ('nimfodora-vifinskaja', 2583),
                           ('valerian-tomskij-kjustendzhijskij', 1345),
                           ('viktor-halkidonskij', 1434), ('sofija-rimskaja', 2934), ('irina-egipetskaja', 2048),
                           ('dorimedont-sinadskij-frigijskij', 1662), ('feopistija-rimskaja', 3120),
                           ('feopist-rimskij', 3119),
                           ('feodor-chernigovskij', 3077), ('andrej-sirakuzskij', 1187), ('petr-sirakuzskij', 2713),
                           ('kallistrat-vizantijskij', 2114), ('marija-radonezhskaja', 2371),
                           ('mark-klavdiopolskij', 2378),
                           ('david-aragvetskij', 4041), ('vakh-rimljanin', 1338), ('evlampij-nikomidijskij', 1691),
                           ('zinaida-tarsijskaja', 1825), ('nazarij-rimljanin', 2493), ('protasij-mediolanskij', 2768),
                           ('iakov-omuchskij', 1856), ('gaij-nikomidijskij', 1484), ('iraklij-adrianopolskij', 2043),
                           ('elisaveta-adrianopolskaja', 4142), ('markian-konstantinopolskij-chtec', 2388),
                           ('kapitolina-kappadokijskaja', 2118), ('klavdij-kilikijskij', 2175),
                           ('neon-kilikijskij', 2506),
                           ('zinovija-egejskaja-kilikijskaja', 1827), ('nikodim-pecherskij', 2540),
                           ('damian-azijskij', 1601),
                           ('pigasij-persidskij', 2718), ('elpidifor-persidskij', 1780),
                           ('epistimija-emesskaja-finikijskaja', 1789),
                           ('markell-drugoj', 2385), ('ioasaf-indijskij', 2002), ('apfija-appija-kolosskaja', 1246),
                           ('evgraf-aleksandrijskij', 1681), ('evgenij-sevastijskij', 1677),
                           ('mardarij-sevastijskij', 2356),
                           ('firs-kesarijskij-vifinskij', 3163), ('hrisogon-rimljanin', 3194),
                           ('satornin-kritskij', 2836),
                           ('gelasij-kritskij', 1493), ('zotik-kritskij', 1838), ('vasilid-kritskij', 1379),
                           ('evgenija-rimskaja', 1680),
                           ('feofil-pecherskij', 3132), ('marionilla-egipetskaja', 2361),
                           ('kandid-trapezundskij', 2117),
                           ('akila-trapezundskij', 1081), ('satir-satur-karfagenskij', 2835),
                           ('avraamij-pechengskij', 1028),
                           ('dorofeja-kesarijskaja-kappadokijskaja', 1666), ('pavla-kesarijskaja-palestinskaja', 2644),
                           ('pavel-ptolemaidskij', 2638), ('david-jaroslavskij', 1592),
                           ('konstantin-jaroslavskij', 2200),
                           ('vasilij-hersonesskij', 1404), ('evgenij-hersonesskij', 1679),
                           ('agafodor-hersonesskij', 1047),
                           ('galina-korinfskaja', 1488), ('trofim-nikomidijskij', 3257), ('hrisanf-rimskij', 3193),
                           ('sergij-savvait', 2871),
                           ('mark-arefusijskij', 2374), ('prokess-rimskij', 2756),
                           ('antonij-vilenskij-litovskij', 1216),
                           ('dioskor-pergijskij-pamfilijskij', 1647), ('dionisij-pergijskij-pamfilijskij', 1640),
                           ('valentin-dorostolskij', 1341), ('alfij-bastijskij', 1134), ('vit-rimskij', 1441),
                           ('mihail-muromskij', 2466),
                           ('iustin-rimskij', 2101), ('klavdij-vizantijskij', 2174), ('pavel-vizantijskij', 2625),
                           ('vassian-pertominskij', 1415), ('manuil-persijanin-khalkidonskij', 2354),
                           ('ipatij-tripolijskij', 2038),
                           ('iulij-mirmidonjanin', 2097), ('petr-v-inochestve-david-muromskij', 2709),
                           ('sergij-valaamskij-1', 2861),
                           ('kosma-rimskij', 2220), ('ioann-jarengskij', 1991), ('adrian-nikomidijskij', 1065),
                           ('aifal-persidskij', 1072),
                           ('ammun-iraklijskij', 1144), ('gleb-v-kreshchenii-david', 1547),
                           ('raisa-iraida-aleksandrijskaja', 2780),
                           ('arhipp-herotopskij-v-honeh', 1282), ('kirill-gortinskij', 2158),
                           ('serapion-pskovskij-spaso-eleazarovskij', 2849),
                           ('evpsihij-kesarijskij-kappadokijskij-drugoj', 1704),
                           ('severian-sevastijskij-drugoj', 2844), ('evdokija-ija-rimljanynja', 1684),
                           ('patermufij-egipetskij-prepodobnomuchenik', 2674), ('iulitta-tarsijskaja', 2098),
                           ('trofim-likijskij', 3016),
                           ('ermipp-nikomidijskij', 1803), ('kosma-kosinskij', 2218), ('favst-dalmatskij', 3024),
                           ('sikst-ii-rimskij', 2877),
                           ('feodor-pecherskij', 3065), ('aleksandr-rimskij-muchenik', 1104),
                           ('fotij-nikomidijskij', 3182),
                           ('erm-rimskij', 1798), ('polien-rimskij', 2734), ('evfrosin-palestinskij', 1745),
                           ('iulian-galatijskij', 2087),
                           ('kornut-nikomidijskij-ikonijskij', 2212), ('filofej-mravinskij-vifinskij', 3158),
                           ('sevastiana-geraklejskaja', 2843), ('ariadna-promisskaja-frigijskaja', 1249),
                           ('foka-sinopskij', 3171),
                           ('foka-vertogradar-sadovnik', 3170), ('vladislav-serbskij', 1456),
                           ('evfrosinija-aleksandrijskaja', 1749),
                           ('savvatij-soloveckij', 2820), ('irodion-iloezerskij', 2059), ('vjacheslav-cheshskij', 1469),
                           ('ierofej-afinskij', 1888), ('petr-kapetolijskij', 2702), ('pavel-preprostyj', 2636),
                           ('dionisij-aleksandrijskij', 1631), ('pelagija-antiohijskaja-deva', 2685),
                           ('poplija-antiohijskaja', 2742),
                           ('vassian-vasilij-konstantinopolskij', 1413),
                           ('domnika-domnina-anazarovskaja-kilikijskaja', 1658),
                           ('florentij-solunjanin', 3169), ('nikita-ispovednik-konstantinopolskij', 2524),
                           ('silvan-gazskij', 2882),
                           ('ioann-suzdalskij', 1981), ('savin-katanskij-sicilijskij', 2825),
                           ('longin-jarengskij', 2289),
                           ('marin-anazarovskij', 2358), ('sadok-persidskij', 2826), ('ilarion-meglinskij', 1900),
                           ('ilarion-pecherskij', 1904), ('ilarion-pskovoezerskij-gdovskij', 1905),
                           ('ignatij-konstantinopolskij', 1871),
                           ('afanasij-i-konstantinopolskij', 1294), ('tavifa-ioppijskaja', 2972),
                           ('feofil-pecherskij-novgorodskij', 3131),
                           ('nestor-solunskij-fessalonikijskij', 2514), ('nestor-letopisec', 2511),
                           ('andrej-smolenskij', 1188),
                           ('arsenij-i-serbskij', 1270), ('kiriak-ierusalimskij', 2151), ('avramij-rostovskij', 1030),
                           ('markian-sirakuzskij', 2390), ('nikandr-gorodnoezerskij', 2516),
                           ('pavel-i-konstantinopolskij', 2629),
                           ('luka-pecherskij', 2294), ('feodot-ankirskij-korchemnik', 3096),
                           ('onisifor-pecherskij', 2604),
                           ('aleksandr-solunskij-fessalonikijskij', 1109), ('milij-persidskij', 2445),
                           ('aleksandr-v-shime-aleksij-nevskij', 1099), ('palladij-aleksandrijskij', 2653),
                           ('irinarh-sevastijskij', 2054),
                           ('paramon-vifinskij', 2663), ('akakij-sinajskij', 1077), ('nektarij-pecherskij', 2504),
                           ('aviv-nekresskij-kahetinskij', 1015), ('andrej-pervozvannyj', 1186),
                           ('afanasij-pecherskij', 1302),
                           ('ise-iessej-cilkanskij', 2073), ('feodor-aleksandrijskij', 3045),
                           ('gennadij-novgorodskij', 1500),
                           ('nil-stolobenskij', 2582), ('antonij-sijskij', 1228), ('daniil-stolpnik', 1609),
                           ('nikon-suhoj', 2577),
                           ('luka-stolpnik', 2296), ('spiridon-trimifuntskij', 2946), ('aleksandr-ierusalimskij', 1092),
                           ('arkadij-novotorzhskij-vjazemskij', 1259), ('stefan-surozhskij', 2964),
                           ('sofija-suzdalskaja', 2936),
                           ('mihail-singell-konstantinopolskij', 2469), ('ilija-muromec', 1911),
                           ('vonifatij-milostivyj', 1460),
                           ('daniil-ii-serbskij', 1607), ('iulianija-vjazemskaja', 2091), ('nifont-kiprskij', 2587),
                           ('pavel-neokesarijskij', 2632), ('feofil-omuchskij', 3129),
                           ('anisija-solunskaja-fessalonikijskaja', 1199),
                           ('timon-bostrijskij', 2990), ('silvestr-pecherskij', 2885), ('evstafij-i-serbskij', 1715),
                           ('apollinarija', 1240),
                           ('grigorij-akritskij', 4009), ('grigorij-pecherskij-zatvornik', 1573),
                           ('isidor-jurevskij-derptskij', 2077),
                           ('abo-tbilisskij', 1002), ('petr-sevastijskij', 2712), ('markian-konstantinopolskij', 2388),
                           ('makarij-pisemskij', 2330), ('savva-i-serbskij', 2807),
                           ('iakov-nizibijskij-nisivijskij', 1855),
                           ('feodul-sinajskij', 3105), ('antonij-chernozerskij', 1230),
                           ('afanasij-sjandemskij-vologodskij', 1307),
                           ('makarij-rimljanin', 2331), ('makarij-pecherskij-postnik', 2329), ('evfimij-velikij', 1731),
                           ('ksenija-v-miru-evsevija-milasskaja', 2234), ('anastasij-persjanin', 1157),
                           ('ksenofont-robejskij', 2238),
                           ('feodosij-totemskij', 3088), ('efrem-novotorzhskij', 1811), ('zinon-pecherskij', 1830),
                           ('fotij-konstantinopolskij', 3180), ('pankratij-pecherskij', 2657),
                           ('prohor-pecherskij', 2770),
                           ('vlasij-sevastijskij', 1457), ('feodora-grecheskaja', 3080), ('isaakij-pecherskij', 2067),
                           ('pafnutij-pecherskij', 2680), ('feodor-pecherskij-molchalivyj', 3064),
                           ('kosma-jahromskij', 2223),
                           ('agapit-sinadskij-frigijskij', 1040), ('flavian-konstantinopolskij', 3165),
                           ('afanasij-ispovednik', 1299),
                           ('aleksandr-konstantinopolskij-pervonachalnik', 1094), ('tarasij-konstantinopolskij', 2978),
                           ('porfirij-gazskij', 2743), ('prokopij-dekapolit', 2761),
                           ('kassian-ioann-kassian-rimljanin', 2126),
                           ('evdokija-iliopolskaja', 1685), ('feodot-kirinejskij', 3098),
                           ('evfalija-leentinskaja-sicilijskaja', 1727),
                           ('gerasim-iordanskij', 1522), ('gerasim-vologodskij', 1521),
                           ('vasilij-vasilko-rostovskij', 1380),
                           ('konon-isavrijskij', 2189), ('konon-mandonskij-pamfilijskij-gradar', 2190),
                           ('pavel-prusiadskij', 2637),
                           ('feofilakt-ispovednik-nikomidijskij', 3135), ('evfimij-novgorodskij', 1734),
                           ('simeon-novyj-bogoslov', 2895),
                           ('savin-ermopolskij-egipetskij', 2824), ('venedikt-nursijskij', 1419),
                           ('serapion-novgorodskij', 2848),
                           ('aristovul-vritanijskij-britanskij', 1252), ('makarij-kaljazinskij', 2319),
                           ('innokentij-komelskij-vologodskij', 1916), ('vassa-pskovo-pecherskaja', 1412),
                           ('iakov-katanskij-sicilijskij', 1853), ('vasilij-ankirskij-presviter', 1382),
                           ('isaakij-dalmatskij', 2064),
                           ('nikon-sicilijskij', 2576), ('irinej-sirmijskij-sremskij-serbskij', 2058),
                           ('vasilij-novyj-konstantinopolskij', 1393), ('bojan-enravot-bolgarskij', 1329),
                           ('ipatij-gangrskij', 2034),
                           ('evfimij-suzdalskij', 1740), ('tit-chudotvorec', 3000), ('nikita-midikijskij', 2525),
                           ('georgij-peloponesskij-malein', 1514), ('platon-studijskij', 2731),
                           ('feodora-solunskaja-fessalonikijskaja', 3084), ('mefodij-moravskij', 2441),
                           ('georgij-mitilenskij', 1510),
                           ('daniil-perejaslavskij', 1606), ('evpsihij-kesarijskij-kappadokijskij', 1704),
                           ('vadim-persidskij', 1336),
                           ('varsonofij-tverskoj-episkop', 1373), ('vasilij-parijskij-ispovednik', 1396),
                           ('artemon-laodikijskij', 1279),
                           ('savva-gotfskij-mussovskij-valahijskij', 2809), ('adrian-korinfskij', 1062),
                           ('ioann-vetkhopeshhernik', 1932),
                           ('aleksandr-oshevenskij', 1100), ('maksimian-maksim-konstantinopolskij', 2346),
                           ('feodor-sikeot-anastasiupolskij', 3068), ('savva-stratilat', 2816),
                           ('aleksij-pecherskij-zatvornik', 4137),
                           ('elisaveta-konstantinopolskaja', 1771), ('silvestr-obnorskij-poshehonskij', 2883),
                           ('vasilij-amasijskij', 1381),
                           ('glafira-amasijskaja', 1543), ('pafnutij-borovskij', 2679), ('makarij-kievskij', 2321),
                           ('feodosij-pecherskij', 3086), ('silvan-gazskij-episkop', 2882),
                           ('varlaam-serpuhovskoj', 1363),
                           ('mihej-radonezhskij', 2475), ('shio-simeon-mgvimskij', 3202), ('isihij-antiohijskij', 2078),
                           ('taisija-egipetskaja', 2973), ('mokij-amfipolskij', 2483),
                           ('rostislav-velikomoravskij', 2797),
                           ('glikerija-novgorodskaja', 1550), ('pavsikakij-pavsakij-sinadskij-frigijskij', 2646),
                           ('isaija-pecherskij', 2070),
                           ('feodor-osvjashchennyj', 3060), ('georgij-ii-mitilenskij', 1510),
                           ('evfrosinija-v-miru-evdokija-moskovskaja', 1751), ('kornilij-komelskij', 2206),
                           ('kornilij-paleostrovskij-oloneckij', 2208),
                           ('dovmont-v-kreshchenii-timofej-pskovskij', 1650),
                           ('ioann-vladimir-serbskij', 1993), ('mihail-sinadskij-frigijskij', 2468),
                           ('evfrosinija-polotskaja-do-kreshhenija-knjazhna-predislava', 1752),
                           ('ferapont-kiprskij', 3137),
                           ('ferapont-sardijskij', 3139), ('ferapont-belozerskij', 3136), ('ignatij-rostovskij', 1878),
                           ('elikonida-solunskaja-fessalonikijskaja', 1773), ('feodosija-konstantinopolskaja', 3094),
                           ('erm-ermij-dalmatskij', 1797), ('mitrofan-konstantinopolskij', 2457),
                           ('kirill-aleksandrijskij', 2155),
                           ('aleksandr-kushtskij', 1096), ('timofej-prusskij', 2995), ('varnava-vetluzhskij', 1368),
                           ('stefan-ozerskij', 2957), ('mstislav-v-kreshchenii-georgij-hrabryj', 2489),
                           ('efrem-ii-serbskij', 1814),
                           ('tihon-medynskij-kaluzhskij', 3005), ('paisij-velikij', 2647), ('gleb-vladimirskij', 1544),
                           ('iulian-tarsijskij', 2089), ('tertij-terentij', 2988), ('agrippina-rimljanynja', 1059),
                           ('fevronija-sirskaja', 3035), ('sampson-strannopriimec', 2830),
                           ('konstantinopolskij-olimpijskij', 2704),
                           ('iuvenalij-juvenalij-ierusalimskij', 2083), ('vasilij-rjazanskij', 1400),
                           ('anatolij-konstantinopolskij', 1165),
                           ('andrej-bogoljubskij', 1178), ('afanasij-afonskij', 1288), ('lampad-irinopolskij', 2256),
                           ('prokopij-do-muchenichestva-neanij-kesarijskij-palestinskij', 2762),
                           ('antonij-pecherskij', 1225),
                           ('kindej-sidskij-pamfilijskij', 2141), ('golinduha-v-kreshchenii-marija-persidskaja', 1551),
                           ('iulian-kenomanijskij', 3246), ('stefan-mahrishchskij', 2953),
                           ('afinogen-pidahfojskij', 1312),
                           ('marina-margarita-antiohijskaja', 2359), ('ioann-pecherskij-mnogostradalnyj', 1962),
                           ('pamva-pecherskij', 2654),
                           ('apollinarij-ravennijskij', 1239), ('polikarp-pecherskij', 2736),
                           ('makarij-zheltovodskij', 2318),
                           ('paraskeva-rimskaja', 2668), ('ioasaf-moskovskij-skripicyn', 2000),
                           ('pavel-ksiropotamskij', 2630),
                           ('serafima-rimskaja', 2859), ('evdokim-kappadokijanin', 1683), ('antonij-rimljanin', 1227),
                           ('evsignij-antiohijskij', 1710), ('dometij-persijanin-sirijskij', 1655),
                           ('pimen-pecherskij', 2723),
                           ('merkurij-smolenskij-pecherskij', 2439), ('emilian-kizicheskij', 1782),
                           ('grigorij-pecherskij-ikonopisec', 1574),
                           ('aleksandr-komanskij', 3247), ('markell-apamejskij', 2383), ('miron-kizicheskij', 2451),
                           ('andrej-stratilat', 1189), ('avraamij-smolenskij', 1031),
                           ('kallinik-i-konstantinopolskij', 2111),
                           ('evtihij-uchenik-ap-ioanna-bogoslova', 1719), ('tation-klavdiopolskij-vifinskij', 2980),
                           ('anna-prorochica', 1206), ('hristofor-rimljanin', 3199),
                           ('fantin-solunskij-fessalonikijskij', 3031),
                           ('gennadij-konstantinopolskij', 1498), ('filimon-gazskij', 3147),
                           ('kifa-ikonijskij-kolofonskij', 2172),
                           ('siluan-solunskij-fessalonikijskij', 2879), ('gaij-efesskij', 1483),
                           ('flegont-marafonskij', 3167),
                           ('ananija-damasskij', 1152), ('sosfen-kolofonskij', 2932), ('prohor-nikomidijskij', 2769),
                           ('timofej', 2991),
                           ('tit-apostol', 2998), ('ruf-fivskij', 2803), ('artema', 1274), ('arhipp-kolosskij', 1281),
                           ('onisifor-kolofonskij', 2602), ('asinkrit-girkanskij', 1284), ('filolog-sinopskij', 3155),
                           ('amplij-diospolskij', 1146), ('narkiss-afinskij', 2494), ('kliment-rimskij', 2183),
                           ('apellij-apelles', 1238),
                           ('rodion-irodion-patrasskij', 2788), ('gedeon-sudija-izrailskij', 1492), ('sofonija', 2938),
                           ('anna-prorochica-mat-proroka-samuila', 1207), ('iov-mnogostradalnyj', 2004), ('ioil', 2008),
                           ('zaharija-serpovidec', 1823), ('elisej', 1775), ('daniil-prorok', 1612),
                           ('ananija-vavilonskij', 1153),
                           ('misail-vavilonskij', 2452), ('avim-makkavej', 1016), ('gurij-makkavej', 1583),
                           ('evsevon-makkavej', 1709),
                           ('markell-makkavej', 2384), ('mian-nikomidijskij', 2444), ('iulian-kandavlskij', 2088),
                           ('iuventin-evventij-antiohijskij', 2084), ('evdoksij-melitinskij', 1688),
                           ('makarij-melitinskij', 2323),
                           ('favst-aleksandrijskij', 3023), ('mitrodora-vifinskaja', 2453),
                           ('gordian-novodunskij', 1555),
                           ('zotik-tomskij-kjustendzhijskij', 1842), ('lukian-tomskij-kjustendzhijskij', 2302),
                           ('sofija-egipetskaja', 2933),
                           ('trofim-sinadskij-frigijskij', 3017), ('savvatij-antiohijskij', 2819),
                           ('agapij-rimskij', 1036),
                           ('ipatij-efesskij', 2035), ('andrej-efesskij', 1179), ('ksanfippa-toledskaja', 2233),
                           ('poliksenija-ispanskaja', 2738), ('ioann-sirakuzskij', 1979), ('antonin-sirakuzskij', 1233),
                           ('kirill-radonezhskij', 2163), ('dada-persidskij', 1595),
                           ('gaveddaj-gavdelas-persidskij', 1470),
                           ('konstantin-aragvetskij', 4042), ('gaij-aleksandrijskij', 1482),
                           ('favst-aleksandrijskij-diakon', 3023),
                           ('herimon-aleksandrijskij', 3190), ('virineja-veronika-edesskaja', 1438),
                           ('davikt-adavkt-efesskij', 1593),
                           ('afanasija-tavenskaja', 1311), ('evlampija-nikomidijskaja', 1692),
                           ('agafodor-sardijskij', 1046),
                           ('agafonika-pergamskaja', 1051), ('gervasij-mediolanskij', 1526),
                           ('kelsij-mediolanskij', 2132),
                           ('veveja-feveja', 1418), ('dasij-nikomidijskij', 1615), ('zotik-nikomidijskij', 1839),
                           ('aleksandr-adrianopolskij', 1087), ('anna-adrianopolskaja', 1200),
                           ('feodotija-adrianopolskaja', 3102),
                           ('glikerija-adrianopolskaja', 1548), ('martirij-konstantinopolskij', 2401),
                           ('erotiida-kappadokijskaja', 1808),
                           ('asterij-kilikijskij', 1286), ('feonilla-kilikijskaja', 3117),
                           ('zinovij-egejskij-kilikijskij', 1826),
                           ('spiridon-pecherskij', 2945), ('kosma-azijskij', 2215), ('akindin-persidskij', 1083),
                           ('affonij-persidskij', 1314), ('anempodist-persidskij', 1197),
                           ('galaktion-emesskij-finikijskij', 1487),
                           ('klavdija-ankirskaja-korinfskaja', 2178), ('matrona-ankirskaja-korinfskaja', 2413),
                           ('zakhej-gadarinskij', 1819),
                           ('anatolij-nikejskij', 1166), ('kikilija-cecilija-rimskaja', 2140),
                           ('orest-sevastijskij', 2612),
                           ('levkij-kesarijskij-vifinskij', 2264), ('apollonij-antinojskij', 1241),
                           ('polievkt-kesarijskij-kappadokijskij', 2732), ('feodul-kritskij', 3103),
                           ('evpor-kritskij', 1700),
                           ('evnikian-kritskij', 1695), ('pompij-kritskij', 2740), ('agafopus-kritskij', 1053),
                           ('evarest-kritskij', 1672),
                           ('iakinf-rimskij', 1844), ('mark-pecherskij-grobokopatel', 2380), ('ioann-pecherskij', 1964),
                           ('feofil-livijskij', 3128), ('ermil-singidonskij-belgradskij', 1801),
                           ('stratonik-singidonskij-belgradskij', 2969),
                           ('evgenij-trapezundskij', 1678), ('valerian-trapezundskij', 1346),
                           ('vitalij-rimljanin', 1443),
                           ('ippolit-ostinskij', 2040), ('koprij-pechengskij', 2204), ('varsonofij-velikij', 1370),
                           ('haralampij-magnezijskij', 3185), ('valentina-kesarijskaja-palestinskaja', 1343),
                           ('marija-vifinskaja', 2362),
                           ('zoja-vifleemskaja', 1843), ('fotinija-svetlana-palestinskaja', 3184),
                           ('iulianija-ptolemaidskaja', 2096),
                           ('efrem-hersonesskij', 1816), ('kapiton-hersonesskij', 2120), ('eferij-hersonesskij', 1809),
                           ('elpidij-hersonesskij', 1779), ('feodora-korinfskaja', 3082),
                           ('evkarpij-nikomidijskij', 1689),
                           ('darija-rimskaja', 1613), ('ioann-savvait', 1973), ('patrikij-savvait', 2677),
                           ('lidija-illirijskaja', 2282),
                           ('iona-persidskij', 2016), ('varahisij-persidskij', 1350), ('kirill-iliopolskij', 2160),
                           ('agafopod-solunskij-fessalonikijskij', 1052), ('feodul-solunskij-fessalonikijskij', 3107),
                           ('iakov-persidskij', 1851), ('martinian-rimskij', 2399), ('ioann-palestinskij', 1960),
                           ('ioann-vilenskij-litovskij', 1933), ('evstafij-vilenskij-litovskij', 1713),
                           ('zotik-nikomidijskij-1', 1839),
                           ('kosma-halkidonskij', 2221), ('feona-nikomidijskij-voin', 3115),
                           ('sokrat-pergijskij-pamfilijskij', 2923),
                           ('anatolij-nikomidijskij', 1167), ('zoja-attalijskaja-pamfilijskaja', 4083),
                           ('timofej-fivaidskij-chtec', 2996),
                           ('mavra-fivaidskaja', 2311), ('patrikij-prusskij-brusskij-vifinskij', 2676),
                           ('falalej-egejskij', 3029),
                           ('konstantin-jaroslav-svjatoslavich-muromskij', 2191), ('feodor-muromskij', 3056),
                           ('lukillian-vizantijskij', 2303), ('ipatij-vizantijskij', 2033),
                           ('dionisij-vizantijskij', 1634),
                           ('marfa-persidskaja', 2411), ('antonina-krodamnskaja', 1234), ('iona-pertominskij', 2017),
                           ('grigorij-avnezhskij', 1558), ('evtropij-konstantinopolskij', 1725),
                           ('savel-persijanin', 2823),
                           ('ismail-persijanin', 2081), ('aristoklij-salaminskij-kiprskij', 1254),
                           ('iakov-menjuzhskij', 1854),
                           ('ioann-menjuzhskij', 1954), ('fevronija-v-inochestve-evfrosinija-muromskaja', 3034),
                           ('german-valaamskij', 1530),
                           ('damian-rimskij', 1603), ('koprij-egipetskij-prepodobnomuchenik', 2203),
                           ('alevtina-valentina-kesarijskaja-palestinskaja', 1085), ('feofil-likijskij', 3128),
                           ('ermolaj-nikomidijskij', 1807), ('ermokrat-nikomidijskij', 1806),
                           ('konstantin-kosinskij', 2197),
                           ('valentin-interamskij-italijskij', 1342), ('dalmat-dalmatskij-konstantinopolskij', 1596),
                           ('lavrentij-rimskij', 2249), ('felikissim-rimskij', 3037), ('vasilij-pecherskij', 1398),
                           ('anikita-nikomidijskij', 1198), ('serapion-rimskij', 2850),
                           ('agapij-kesarijskij-palestinskij', 1035),
                           ('natalija-nikomidijskaja', 2495), ('ioann-postnik', 1965), ('feoktist-palestinskij', 3111),
                           ('domnin-solunskij-fessalonikijskij', 1660), ('mihail-zovijskij-sevastijskij', 2459),
                           ('evfimij-novyj', 1737),
                           ('lukian-antiohijskij', 2299), ('andrej-kritskij', 1182), ('uar-egipetskij', 3018),
                           ('merkurij-smolenskij', 2438),
                           ('markell-apamejskij-igumen', 2383), ('sinklitikija-aleksandrijskaja', 2912),
                           ('stefan-triglijskij', 2965),
                           ('hristofor-likijskij', 3198), ('mefodij-konstantinopolskij', 2440),
                           ('olga-v-kreshchenii-elena', 2597),
                           ('averkij-ierapolskij', 1012), ('ioannikij-velikij', 1994), ('lazar-galisijskij', 2252),
                           ('matrona-konstantinopolskaja', 2414), ('varlaam-antiohiec', 1356),
                           ('ekaterina-aleksandrijskaja', 1756),
                           ('pavel-latrijskij', 2631), ('feoktist-kukumskij', 3109),
                           ('domnika-konstantinopolskaja', 1659),
                           ('neofit-nikejskij', 2510), ('ilarion-novyj-pelikitskij', 1902),
                           ('akakij-melitinskij', 1074),
                           ('akilina-starshaja', 1082), ('trifillij-levkusijskij-kiprskij', 3011),
                           ('andrej-kritskij-svjatitel', 1182),
                           ('marfa-antiohijskaja', 2406), ('mihail-malein', 2463), ('dij-konstantinopolskij', 1618),
                           ('marfa-kappadokijskaja', 2409), ('mamant-kesarijskij-kappadokijskij', 2350),
                           ('anfim-nikomidijskij', 1237),
                           ('urvan-antiohijskij', 3020), ('prilidian-antiohijskij', 2751), ('matfej-pecherskij', 2419),
                           ('tarah-anazarvskij', 2979), ('ioann-palestinskij-voin', 1960), ('sarvil-sirijskij', 2833),
                           ('ieraks-sirijskij', 1883), ('marija-hidanskaja', 2372),
                           ('iosif-persidskij-presviter', 2027),
                           ('onisifor-muchenik', 2603), ('porfirij', 2745), ('viktor-damasskij', 1432),
                           ('stefanida-damasskaja', 2967),
                           ('gurij-edesskij', 1581), ('samon-edesskij', 2829),
                           ('feona-v-kreshchenii-sinesij-nikomidijskij', 3115),
                           ('gennadij-vazheozerskij', 3245), ('konstantin-ammorejskij-frigijskij', 2192),
                           ('feofil-ammorejskij-frigijskij', 3127), ('agapija-akvilejskaja', 1041),
                           ('hionija-akvilejskaja', 3191),
                           ('maksim-dorostolskij-ozovijskij', 2339), ('ruf-kizicheskij', 2804),
                           ('feostih-kizicheskij', 3121),
                           ('magn-kizicheskij', 2312), ('anatolij-pecherskij-zatvornik', 1171),
                           ('prokl-kaliptskij', 2757),
                           ('ilarij-kaliptskij', 1895), ('vavila-antiohijskij', 1334), ('eppolonij-antiohijskij', 1793),
                           ('damian-pecherskij', 1602), ('ieremija-pecherskij', 1884), ('prov-anazarvskij', 2755),
                           ('andronik-anazarvskij', 1192), ('kleopatra-palestinskaja', 2181),
                           ('terentij-sirijskij', 2987),
                           ('feodul-sirijskij', 3106), ('avraamij-zatvornik', 1025), ('nikandr-mirskij', 2517),
                           ('ermej', 1799),
                           ('evstolija-konstantinopolskaja', 1716), ('feodora-grecheskaja-carica', 3080),
                           ('aviv-edesskij', 1014),
                           ('roman-kesarijskij', 2789), ('varvara-iliopolskaja', 1353),
                           ('feopempt-nikomidijskij', 3118),
                           ('manuil-adrianopolskij', 2353), ('sionij-adrianopolskij', 2913),
                           ('agafangel-rimljanin', 1042),
                           ('nikifor-vazheozerskij', 3244), ('feodor-ammorejskij-frigijskij', 3047),
                           ('irina-akvilejskaja', 2047),
                           ('avdelaj-selevkijskij', 1007), ('antipatr-kizicheskij', 1211), ('artema-kizicheskij', 1275),
                           ('iulianija-moskovskaja', 2093), ('evpraksija-moskovskaja', 1702),
                           ('anatolij-pecherskij', 1171),
                           ('daniil-nikopolskij-armjanskij', 4117), ('vassa-alonskaja', 1411),
                           ('ioakim-bogootec', 1921),
                           ('diodor-laodikijskij-sirskij', 1629), ('didim-laodikijskij-sirskij', 1617),
                           ('prisk-kesarijskij-palestinskij', 2752), ('ripsimija-armjanskaja', 2787),
                           ('gaianija-armjanskaja', 1481),
                           ('leontij-kilikijskij', 2274), ('anfim-kilikijskij', 1236), ('evtropij-kilikijskij', 1724),
                           ('marija-azijskaja', 2364), ('markell', 2385), ('maksimilian-efesskij', 2347),
                           ('iamvlih-efesskij', 1862),
                           ('martinian-efesskij', 2397), ('ioann-efesskij', 1938), ('dionisij-efesskij', 1636)]
    for saint_slug, pravicon_saint_id in pravicon_saints_ids:
        saint: models.Saint = crud.saint.get_by_slug(db, slug=saint_slug)
        pravicon_saint_days: list[date] = __collect.collect_pravicon_saint_days(
            session,
            pravicon_saint_id=pravicon_saint_id
        )
        if not pravicon_saint_days:
            logging.warning(f'pravicon_saint_id {pravicon_saint_id}')
            continue
        saint_days: list[date] = [int_date2date(holiday.day.month, day=holiday.day.day)
                                  for holiday in saint.holidays
                                  if holiday.day]
        saint_days: list[date] = __set_base_year_for_days(saint_days)
        pravicon_saint_days: list[date] = __set_base_year_for_days(pravicon_saint_days)
        if not set(saint_days) & set(pravicon_saint_days):
            logging.error(saint.slug)
            logging.error(pravicon_saint_id)
            logging.error(saint_days)
            logging.error(pravicon_saint_days)
            logging.warning('- - -')
